CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" int NOT NULL,
  "email" varchar(25) UNIQUE NOT NULL,
  "password" varchar(25) NOT NULL,
  "age" int NOT NULL,
  "rol" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "url" varchar(25) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(25) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" varchar(25) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(25) NOT NULL
);

CREATE TABLE "title" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL
);

CREATE TABLE "description" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(50) NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher" varchar(25) NOT NULL
);

CREATE TABLE "name" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "age" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "age" int NOT NULL
);

CREATE TABLE "course_general" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_description" int NOT NULL,
  "course_level" int NOT NULL,
  "course_teacher" int NOT NULL,
  "course_user" int NOT NULL,
  "course_category" int NOT NULL,
  "course_videos" int NOT NULL,
  "course_title" int NOT NULL
);

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_level") REFERENCES "level" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_teacher") REFERENCES "teacher" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_title") REFERENCES "title" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_videos") REFERENCES "course_videos" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_category") REFERENCES "categories" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_description") REFERENCES "description" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_user") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol") REFERENCES "roles" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("name") REFERENCES "name" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("age") REFERENCES "age" ("id");



entregable1=# INSERT INTO description (id, description) VALUES (1, 'fundamentos'), (2,'Diseño y Desarrollo');
INSERT 0 2
entregable1=# SELECT*FROM description;
 id |     description
----+---------------------
  1 | fundamentos
  2 | Diseño y Desarrollo
(2 filas)


entregable1=# INSERT INTO roles (id, rol) VALUES (1, 'Student'), (2,'Teacher'),(3 , 'Admin' );
INSERT 0 3
entregable1=# SELECT*FROM roles;
 id |   rol
----+---------
  1 | Student
  2 | Teacher
  3 | Admin
(3 filas)

entregable1=# INSERT INTO age (id, age) VALUES (1,32);
INSERT 0 1
entregable1=# INSERT INTO age (id, age) VALUES (2,22);
INSERT 0 1
entregable1=# SELECT*FROM age;
 id | age
----+-----
  1 |  32
  2 |  22
(2 filas)

entregable1=# INSERT INTO users (id, name ,email, password, age, rol) VALUES (2,2 ,'maria@gmail.com',312356, 22, 1);
INSERT 0 1
entregable1=# SELECT*FROM users;
 id | name |      email      | password | age | rol
----+------+-----------------+----------+-----+-----
  1 |    1 | jose@gmail.com  | 12356    |  32 |   1
  2 |    2 | maria@gmail.com | 312356   |  22 |   1
(2 filas)

entregable1=# INSERT INTO level (id,level) VALUES (3,'avanzado');
INSERT 0 1
entregable1=# SELECT*FROM level;
 id |     level
----+---------------
  1 | principiantes
  2 | intermedio
  3 | avanzado
(3 filas)

entregable1=# INSERT INTO categories (id, category) VALUES (2, 'Diseño web');
INSERT 0 1
entregable1=# SELECT*FROM categories;
 id |  category
----+-------------
  1 | programcion
  2 | Diseño web
(2 filas)


entregable1=# SELECT*FROM title;
 id |   title
----+------------
  1 | typeScript
  2 | CSS
(2 filas)


entregable1=# SELECT*FROM course_videos;
 id |   title    |        url
----+------------+--------------------
  1 | TypeScript | www.typescript.com
  2 | CSS        | www.css.com
(2 filas)


entregable1=# SELECT*FROM teacher;
 id | teacher
----+---------
  1 | Pedro
  2 | Maria
(2 filas)

entregable1=# SELECT*FROM name;
 id |  name
----+---------
  1 | Eduardo
  2 | Carlos
(2 filas)






entregable1=# SELECT course_general.id , course_title , course_description, level.level , users.name , categories.category , course_videos.title , course_videos.url , teacher.teacher , description.description FROM course_general JOIN level ON level.id = course_general.course_level JOIN users ON users.id=course_general.course_user JOIN categories ON categories.id = course_general.course_category JOIN course_videos ON course_videos.id=course_general.course_videos JOIN teacher ON teacher.id= course_general.course_teacher JOIN description ON description.id=course_general.course_description;
 id | course_title | course_description |     level     | name |  category   |   title    |        url         | teacher |     description
----+--------------+--------------------+---------------+------+-------------+------------+--------------------+---------+---------------------
  1 |            1 |                  1 | principiantes |    1 | programcion | TypeScript | www.typescript.com | Pedro   | fundamentos
  2 |            2 |                  2 | intermedio    |    2 | Diseño web  | CSS        | www.css.com        | Maria   | Diseño y Desarrollo







entregable1=# SELECT*FROM course_general;
 id | course_description | course_level | course_teacher | course_user | course_category | course_videos | course_title
----+--------------------+--------------+----------------+-------------+-----------------+---------------+--------------
  1 |                  1 |            1 |              1 |           1 |               1 |             1 |            1
  2 |                  2 |            2 |              2 |           2 |               2 |             2 |            2


  